// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALKF6gfdybyfZZ4KbPrQOs41CE8S8zf3U',
    appId: '1:486734565059:web:f9dc96a3c0e77239261c76',
    messagingSenderId: '486734565059',
    projectId: 'mainrvchat',
    authDomain: 'mainrvchat.firebaseapp.com',
    storageBucket: 'mainrvchat.appspot.com',
    measurementId: 'G-4M865ZXZ98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTEReTP56Dh5auN2ev7c-vWBVSa084XPE',
    appId: '1:486734565059:android:39054ef44ae1421c261c76',
    messagingSenderId: '486734565059',
    projectId: 'mainrvchat',
    storageBucket: 'mainrvchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURM-bb3OdaGoRnR05f25j6Xw2QOSU5JA',
    appId: '1:486734565059:ios:5d7034b3697aa0cd261c76',
    messagingSenderId: '486734565059',
    projectId: 'mainrvchat',
    storageBucket: 'mainrvchat.appspot.com',
    iosClientId: '486734565059-rlg1cpdqde741e1nnlp4u9mbu3u63sqn.apps.googleusercontent.com',
    iosBundleId: 'com.alphadron.rvchat',
  );
}
